name: Push to Docker Hub

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: d34dc3n73r
          password: ${{ secrets.DOCKER_HUB }}
      -
        name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: d34dc3n73r/netdata-glibc:latest


#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: push to docker hub
#      uses: docker/build-push-action@v1
#      with:
#        username: d34dc3n73r
#        password: ${{ secrets.DOCKER_HUB }}
#       repository: d34dc3n73r/netdata-glibc
#       tags: latest
