name: Push to Docker Hub

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: d34dc3n73r
          password: ${{ secrets.DOCKER_HUB }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: d34dc3n73r/netdata-glibc:latest
